/**
 * Easy Cash By KPV
 * The Easy Cash API
 *
 * The version of the OpenAPI document: V 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.EasyCashByKpv);
  }
}(this, function(expect, EasyCashByKpv) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new EasyCashByKpv.CreateCatDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateCatDto', function() {
    it('should create an instance of CreateCatDto', function() {
      // uncomment below and update the code to test CreateCatDto
      //var instance = new EasyCashByKpv.CreateCatDto();
      //expect(instance).to.be.a(EasyCashByKpv.CreateCatDto);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new EasyCashByKpv.CreateCatDto();
      //expect(instance).to.be();
    });

    it('should have the property age (base name: "age")', function() {
      // uncomment below and update the code to test the property age
      //var instance = new EasyCashByKpv.CreateCatDto();
      //expect(instance).to.be();
    });

    it('should have the property breed (base name: "breed")', function() {
      // uncomment below and update the code to test the property breed
      //var instance = new EasyCashByKpv.CreateCatDto();
      //expect(instance).to.be();
    });

  });

}));
